export const Icons = {
  Menu: () => <span>☰</span>,
  X: () => <span>✕</span>,
  Search: () => <span>🔍</span>,
  Bell: () => <span>🔔</span>,
  Settings: () => <span>⚙️</span>,
  LogOut: () => <span>🚪</span>,
  Eye: () => <span>👁️</span>,
  EyeOff: () => <span>🙈</span>,
  Loader2: ({ className }: { className?: string }) => <span className={className}>⏳</span>,
  LayoutDashboard: () => <span>📊</span>,
  FileText: () => <span>📄</span>,
  BarChart3: () => <span>📈</span>,
  MessageSquare: () => <span>💬</span>,
  FileBarChart: () => <span>📋</span>,
  Plus: () => <span>➕</span>,
  Download: () => <span>⬇️</span>,
  Calendar: () => <span>📅</span>,
  Building: () => <span>🏢</span>,
  DollarSign: () => <span>💰</span>,
  Clock: () => <span>🕐</span>,
  TrendingUp: () => <span>📈</span>,
  TrendingDown: () => <span>📉</span>,
  AlertTriangle: () => <span>⚠️</span>,
  AlertCircle: () => <span>⚠️</span>,
  Filter: () => <span>🔽</span>,
  Send: () => <span>📤</span>,
  Bot: () => <span>🤖</span>,
  User: () => <span>👤</span>,
  Lightbulb: () => <span>💡</span>,
  Target: () => <span>🎯</span>,
}

// Added missing icon exports
export const Menu = Icons.Menu
export const X = Icons.X
export const Search = Icons.Search
export const Bell = Icons.Bell
export const Settings = Icons.Settings
export const LogOut = Icons.LogOut
export const Eye = Icons.Eye
export const EyeOff = Icons.EyeOff
export const Loader2 = Icons.Loader2
export const LayoutDashboard = Icons.LayoutDashboard
export const FileText = Icons.FileText
export const BarChart3 = Icons.BarChart3
export const MessageSquare = Icons.MessageSquare
export const FileBarChart = Icons.FileBarChart
export const Plus = Icons.Plus
export const Download = Icons.Download
export const Calendar = Icons.Calendar
export const Building = Icons.Building
export const DollarSign = Icons.DollarSign
export const Clock = Icons.Clock
export const TrendingUp = Icons.TrendingUp
export const TrendingDown = Icons.TrendingDown
export const AlertTriangle = Icons.AlertTriangle
export const AlertCircle = Icons.AlertCircle
export const Filter = Icons.Filter
export const Send = Icons.Send
export const Bot = Icons.Bot
export const User = Icons.User
export const Lightbulb = Icons.Lightbulb
export const Target = Icons.Target
